[package]
name = "learning_rust_project"
version = "0.1.0"
authors = ["jason"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2="0.34.0"
rand="0.7.3"
